### ISSUE TITLE
Parsing returns individual characters instead of words.

### ISSUE THREAD

**Issue by joshinryz** [ljm625/syntaxnet-rest-api#10]
When running a query, it seems that syntaxnet is parsing the letters , not words.

[user@localhost ~]$ curl -H "Content-Type: application/json" -X POST -d '{"strings":"Bob"}' http://localhost:9000/api/v1/query
 
Returns ->
[
	{
		"category": "",
		"pos_tag": "NNP",
		"word": "B",
		"dep": "root",
		"break_level": 0,
		"fpos": "PROPN++NNP",
		"number": "Sing",
		"label": "root"
	},
	{
		"category": "",
		"case": "Nom",
		"word": "o",
		"prontype": "Prs",
		"dep": "root",
		"break_level": 0,
		"pos_tag": "PRP",
		"fpos": "PRON++PRP",
		"number": "Sing",
		"label": "root",
		"person": "1"
	},
	{
		"category": "",
		"pos_tag": "LS",
		"word": "b",
		"dep": "root",
		"break_level": 0,
		"fpos": "X++LS",
		"label": "root"
	}
]

**Comment by ljm625** [comment]
Hi, seems like this issue only happen when you submit a single word, so the result is reasonable, since we can't do NLP on single word..

**Comment by Habitats** [comment]
It happens regardless.

```
{

   "strings": ["Google is awesome!","Syntaxnet is Cool"]

}
```

outputs 
```
[
    {
        "pos_tag": "NNP",
        "dep": "ROOT",
        "contains": [],
        "name": "G"
    },
    {
        "pos_tag": "NFP",
        "dep": "ROOT",
        "contains": [],
        "name": "o"
    },
    {
        "pos_tag": "NFP",
        "dep": "ROOT",
        "contains": [],
        "name": "o"
    },
    {
        "pos_tag": "NFP",
        "dep": "ROOT",
        "contains": [],
        "name": "g"
    },
    {
        "pos_tag": "NNP",
        "dep": "ROOT",
        "contains": [],
        "name": "l"
    },
    {
        "pos_tag": "NFP",
        "dep": "ROOT",
        "contains": [],
        "name": "e"
    },
    {
        "pos_tag": "PRP",
        "dep": "ROOT",
        "contains": [],
        "name": "i"
    },
    {
        "pos_tag": "VBZ",
        "dep": "ROOT",
        "contains": [],
        "name": "s"
    },
    {
        "pos_tag": "DT",
        "dep": "ROOT",
        "contains": [],
        "name": "a"
    },
    {
        "pos_tag": "IN",
        "dep": "ROOT",
        "contains": [],
        "name": "w"
    },
    {
        "pos_tag": "NFP",
        "dep": "ROOT",
        "contains": [],
        "name": "e"
    },
    {
        "pos_tag": "VBZ",
        "dep": "ROOT",
        "contains": [],
        "name": "s"
    },
    {
        "pos_tag": "NFP",
        "dep": "ROOT",
        "contains": [],
        "name": "o"
    },
    {
        "pos_tag": "NN",
        "dep": "ROOT",
        "contains": [],
        "name": "m"
    },
    {
        "pos_tag": "NFP",
        "dep": "ROOT",
        "contains": [],
        "name": "e"
    },
    {
        "pos_tag": ".",
        "dep": "ROOT",
        "contains": [],
        "name": "!"
    }
]
```

**Comment by ljm625** [comment]
sorry on my side it's working pretty fine, will look into it later, in the meantime if you can provide me your request using curl command, that will be pretty helpful, and also, are you using the docker precompiled image or you are building using the dockerfile?

**Comment by Habitats** [comment]
I've tried both building it myself, and using the precompiled. I'm using postman for my requests.

```
curl -X POST \
  http://localhost:9000/api/v1/query \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{

   "strings": ["Google is awesome!","Syntaxnet is Cool"]

}'
```

**Comment by Habitats** [comment]
I get a similar issue here: https://github.com/ljm625/syntaxnet-rest-api/issues/11

**Comment by ljm625** [comment]
Fixed in the latest commit

**Comment by Habitats** [comment]
Awesome!
