### ISSUE TITLE
Getting wrong JSON output 

### ISSUE THREAD

**Issue by shrikant14** [ljm625/syntaxnet-rest-api#13]
I am running the syntaxnet-rest-api docker container and when I POST to http://localhost:9000/api/v1/query/English with data { "strings": ["Google is awesome!","Syntaxnet is Cool"] }.
I am getting the wrong output: 

**OUTPUT:**
[{"pos_tag": "NNP", **"name": "G"**, "dep": "ROOT", "fPOS": "PROPN++NNP", "Number": "Sing", "pos": "PROPN"}, {"pos_tag"
: "UH", "name": "o", "dep": "ROOT", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag": "UH", "name": "o", "dep": "ROOT
", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag": "NNP", "name": "g", "dep": "ROOT", "fPOS": "INTJ++UH", "pos": "P
ROPN"}, {"pos_tag": "UH", "name": "l", "dep": "ROOT", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag": "UH", "name":
 "e", "dep": "ROOT", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag": "UH", "name": "i", "dep": "ROOT", "fPOS": "INT
J++UH", "pos": "INTJ"}, {"pos_tag": "UH", "name": "s", "dep": "ROOT", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag
": "DT", "PronType": "Art", "dep": "ROOT", "Definite": "Ind", "fPOS": "DET++DT", "pos": "DET", "name": "a"}, {"pos_
tag": "UH", "name": "w", "dep": "ROOT", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag": "UH", "name": "e", "dep": "
ROOT", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag": "UH", "name": "s", "dep": "ROOT", "fPOS": "INTJ++UH", "pos":
 "INTJ"}, {"pos_tag": "UH", "name": "o", "dep": "ROOT", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag": "NN", "name
": "m", "dep": "ROOT", "fPOS": "NOUN++NN", "Number": "Sing", "pos": "NOUN"}, {"pos_tag": "UH", "name": "e", "dep": 
"ROOT", "fPOS": "INTJ++UH", "pos": "INTJ"}, {"pos_tag": ".", "name": "!", "dep": "ROOT", "fPOS": "PUNCT++.", "pos":
 "PUNCT"}]

**Comment by ljm625** [comment]
Hi there, this is actually an already fixed issue, #11 and it should already been fixed. could you please provide me which image you are using, the one compiled by the dockerfile yourself, or the one on ljm625/syntaxnet-rest-api:dragnn ?

**Comment by shrikant14** [comment]
Hi, I am using the one on ljm625/syntaxnet-rest-api.

**Comment by ljm625** [comment]
Okay, I figured out why, pls use ljm625/syntaxnet-rest-api:**dragnn**, since by default it's using the **latest** branch which is slower and not recommended (also it has the bug that is fixed in dragnn branch). I will fix the master branch as well, Thanks
