### ISSUE TITLE
"500 Internal Server Error" when trying to use Russian-SynTagRus language model.

### ISSUE THREAD

**Issue by malakhovks** [ljm625/syntaxnet-rest-api#2]
I'm trying to use **Russian-SynTagRus** language model and get **500 Internal Server Error.**
I think there is some encoding issues with cyrillic symbols processing.
Most likely for processing strings with Cyrillic characters need to use Unicode, something like that for string processing:

```Python
data = u"""
Привет , как твои дела ?
Использование кириллических символов .
"""
```
or in Dockerfile to setup locales
```
RUN \
echo u_RU.UTF-8 UTF-8 > /etc/locale.gen && \
locale-gen "ru_RU.UTF-8" && \
echo 'LANG="ru_RU.UTF-8"'>/etc/default/locale && \
dpkg-reconfigure --frontend=noninteractive locales && \
update-locale LC_ALL=ru_RU.UTF-8 LANG=ru_RU.UTF-8  

ENV LANG ru_RU.UTF-8
```

**Comment by ljm625** [comment]
Thanks for the feedback,will try to fix these encoding issues 👍

**Comment by ljm625** [comment]
should be fixed, pls try again ;)

**Comment by malakhovks** [comment]
Now it does not work, even If insert the English model using parsey_universal:
receive instant response from the server **500 Internal Server Error.**

My path to English model folder
```/home/malakhovks/SyntaxNet/English```
So i use command to run model
```docker run -p 9000:9000 -v /home/malakhovks/SyntaxNet:/models -d ljm625/syntaxnet-rest-api```
And then i send POST request to
```http://178.151.51.73:223/api/v1/query/English```

**Comment by ljm625** [comment]
Thanks for the feedback again, it is a permission issue, I tested it with Russian and confirmed it's fixed :P 
`[
  {
    "pos_tag": "NOUN++NN",
    "dep": "ROOT",
    "contains": [
      {
        "pos_tag": "NOUN++NN",
        "dep": "nmod",
        "contains": [
          {
            "pos_tag": "ADJ++JJL",
            "dep": "amod",
            "name": "кириллических"
          }
        ],
        "name": "символов"
      }
    ],
    "name": "Использование"
  }
]`
Here is the result from my test. 
If there's any issue, please feel free to submit, really appreciate.

**Comment by malakhovks** [comment]
Yep, it's fine now :P
Thanks!
