### ISSUE TITLE
add in JSON output format support of the all list of morphological features tags

### ISSUE THREAD

**Issue by malakhovks** [ljm625/syntaxnet-rest-api#3]
One of the most important column in CoNLL-U output file is **6 column** -  **List of morphological features**
(FEATS: List of morphological features [http://universaldependencies.org/u/feat/index.html](url))

Only pos_tag (fPOS in CoNLL-U) is available in your output json.

**List of morphological features tags** ( also avaliable here [http://universaldependencies.org/u/feat/index.html](url)):
* Abbr: abbreviation
* Animacy: animacy
* Aspect: aspect
* Case: case
* Definite: definiteness or state
* Degree: degree of comparison
* Evident: evidentiality
* Foreign: is this a foreign word?
* Gender: gender
* Mood: mood
* NumType: numeral type
* Number: number
* Person: person
* Polarity: polarity
* Polite: politeness
* Poss: possessive
* PronType: pronominal type
* Reflex: reflexive
* Tense: tense
* VerbForm: form of verb or deverbative
* Voice: voice

**Comment by ljm625** [comment]
Thanks for the info, this will be a new feature, will work on this..

**Comment by ljm625** [comment]
It contains these info now, please check the latest README
