### ISSUE TITLE
I wonder if there is a part that needs to be set separately when trying to insert another language pack.

### ISSUE THREAD

**Issue by tylee33** [ljm625/syntaxnet-rest-api#6]
I am testing syntexnet applying Korean using your source.
In the dockerfile, I wonder that there is no part to learn with the language set.
Looking at the source, it seems that the shell script located in parser.py works by referring to the path of the config file.
Custom_parse.sh seems to be similar to demo.sh which is automatically generated by syntexnet.

I wonder if there is a part that needs to be set separately when trying to insert another language pack.

**Comment by ljm625** [comment]
Hi,
Basically if you want to use a language pack, please download the pretrained model https://github.com/tensorflow/models/blob/master/syntaxnet/universal.md and just follow the instructions in the [readme](https://github.com/ljm625/syntaxnet-rest-api/blob/master/README.md) which basically mount the folder which contain this module to the docker container, and the script will try to use the model if you do a rest.

**Comment by ljm625** [comment]
If you want to train your own model, please follow the guide on the syntaxnet repo and after that you can probably use the model in the api wrapper
