### ISSUE TITLE
Server CORS (CROSS-ORIGIN RESOURCE SHARING) requests handling issue (DRAGNN branch).

### ISSUE THREAD

**Issue by malakhovks** [ljm625/syntaxnet-rest-api#8]
##### Server CORS (CROSS-ORIGIN RESOURCE SHARING) requests handling issue (DRAGNN branch).
There will be great to add possibility to server to handling CORS requests.
In my case, the parsing server is working behind a specially designed queue server, and there is no such big problem. But to work with the parsing server directly, you need to add headers in server code that includes CORS support:
`('Access-Control-Allow-Origin: *');  
('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');`

**Comment by ljm625** [comment]
yep, that's a very good suggestion, will just add a few lines of code and fix it ;)

**Comment by malakhovks** [comment]
Ok will wait

**Comment by ljm625** [comment]
should be fixed
